// This file is generated from scripts/default-lang.ts, don't modify, run npm run generate:lang
export enum Lang {
    TITLE = 'TITLE',
    PAGE_CONTACT_SUBHEADER_ADDRESS = 'PAGE_CONTACT_SUBHEADER_ADDRESS',
    PAGE_CONTACT_SUBHEADER_EMAIL = 'PAGE_CONTACT_SUBHEADER_EMAIL',
    PAGE_CONTACT_SUBHEADER_PHONE = 'PAGE_CONTACT_SUBHEADER_PHONE',
    COMPANY_NAME = 'COMPANY_NAME',
    COMPANY_IC = 'COMPANY_IC',
    COMPANY_DIC = 'COMPANY_DIC',
    COMPANY_BANKACCOUNT = 'COMPANY_BANKACCOUNT',
    TRAINING_REFERENCES = 'TRAINING_REFERENCES',
    HOME_REFERENCES = 'HOME_REFERENCES',
    FOOTER_ABOUT_COMPANY = 'FOOTER_ABOUT_COMPANY',
    FOOTER_WEB_MAP = 'FOOTER_WEB_MAP',
}
